### ISSUE TITLE
create background logo image

### ISSUE THREAD

**Issue by kirstin** [kirstin/kirstinheidler.co.uk#1]
600x80px - das Feeling responsive Bild über dem schwimmer

https://kirstin.github.io/kirstinheidler.co.uk-data/images/header_unsplash_12.jpg:
![https://kirstin.github.io/kirstinheidler.co.uk-data/images/header_unsplash_12.jpg](https://kirstin.github.io/kirstinheidler.co.uk-data/images/header_unsplash_12.jpg)

**Comment by niccokunzmann** [comment]
Image with dove
