### ISSUE TITLE
title shown as tab-title to be Kirstin Heidler

### ISSUE THREAD

**Issue by kirstin** [kirstin/kirstinheidler.co.uk#10]
Currently the title of the tab begins with "building a culture of peace"
I'd like it to begin with Kirstin Heidler.

**Comment by niccokunzmann** [comment]
Done, please review.

**Comment by niccokunzmann** [comment]
Not done...
![image](https://user-images.githubusercontent.com/564768/166342360-b6003632-82e0-42f6-a601-2a891f6ac8bb.png)
![image](https://user-images.githubusercontent.com/564768/166342418-4351cd6d-2d55-42c6-b1a1-e3fcdbf6b155.png)

It switches at 640
