### ISSUE TITLE
Web search kirstin and consolidate

### ISSUE THREAD

**Issue by niccokunzmann** [kirstin/kirstinheidler.co.uk#18]
Where we find kirstin, we should direct message to this new url so people know where to look.

Edit:
- [x] speakerinnen.org
- [x] linked in 
- [x] facebook
- [ ] research gate
- [x] seeds of nonviolence

**Comment by niccokunzmann** [comment]
@kirstin, please see the list and update the pages with references to your website.

**Comment by kirstin** [comment]
Cannot do research gate... I think that account is linked to an email address I have no access to any longer.
