### ISSUE TITLE
tracking?

### ISSUE THREAD

**Issue by kirstin** [kirstin/kirstinheidler.co.uk#2]
google_site_verification        : 'TODO'
bing_webmastertools_id          : 'TODO'

@niccokunzmann

**Comment by niccokunzmann** [comment]
Do you care about page statistics? Google also tells us which problems the site has.

**Comment by kirstin** [comment]
I don't know... please tell me more about the specifics and pros and cons.

**Comment by niccokunzmann** [comment]
first, it is no essential but nice to have so it can be closed right now.

Second: If you want to know what people search for when before they click your site, this is something you can use. You do not have to embed any tracking in your website. Google and Bing let you have a part of their data. They also tell me specifics about what they would like changed so the site makes a better mobile experience. Costs: 30min with Internet/(Google|Bing)

**Comment by kirstin** [comment]
Might be interesting what search terms people used...

**Comment by niccokunzmann** [comment]
added google site verification and bing webmaster tools. We can have a look after a while.
