### ISSUE TITLE
Safari

### ISSUE THREAD

**Issue by niccokunzmann** [kirstin/kirstinheidler.co.uk#24]
There are complaints about the images in Safari
- [ ] install safari
- [ ] check with safari

**Comment by niccokunzmann** [comment]
So, I changed how the images are placed to a more compatible version with old browsers. You can tell her to check again or we check ourselves.

**Comment by kirstin** [comment]
I've looked for it. Seems like you cannot currently install Safari on Windows!
I can ask Penny to check with her mac book next time I see her, next week Tuesday.

**Comment by kirstin** [comment]
I can also ask Annie again

**Comment by kirstin** [comment]
The test on Penny's laptop worked. Images fine.
