### ISSUE TITLE
Bring Logo into Header and Footer

### ISSUE THREAD

**Issue by kirstin** [kirstin/kirstinheidler.co.uk#31]
The logo should be somehow brought to more prominence on the website.

**Comment by niccokunzmann** [comment]
Why?

Also, are the SVG and others files in the data Repo? I need them to do that.

**Comment by niccokunzmann** [comment]
@kirstin please upload all the relevant logo files to the data repo from your computer.

**Comment by kirstin** [comment]
All are uploaded. I'd like to have the Logo in the black footer
