### ISSUE TITLE
round linknext to github

### ISSUE THREAD

**Issue by kirstin** [kirstin/kirstinheidler.co.uk#4]
- CTW
- nvc matters

**Comment by niccokunzmann** [comment]
Please provide the links.

**Comment by kirstin** [comment]
ctw: https://ctw-uk.com
nvc-uk : https://nvc-uk.com

NVC Matters doesn't have its own web page.

**Comment by niccokunzmann** [comment]
@kirstin I added the two links

- there is not icon for them so I added the browser icon
- I use fontawesome at the moment. https://fontawesome.com/icons/browser?s=solid

Maybe your network should have its own page?

Please review.|

**Comment by kirstin** [comment]
What do you meant with "your network"?

And where are the links you added so I can review?

**Comment by niccokunzmann** [comment]
They are at the bottom of the page.

**Comment by kirstin** [comment]
Picture for NVC Matters: https://nvc-uk.com/wp-content/uploads/2021/06/NVC-Matters-UK-Logo.png
Logo for CTW in Data Repo
